workspaceLocation: C:/Users/Uma Ramanthan/IdeaProjects/

#https://medium.freecodecamp.org/node-js-child-processes-everything-you-need-to-know-e69498fe970a
#https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js
#https://eclipsesource.com/blogs/2016/07/20/running-node-js-on-the-jvm/
#https://dzone.com/articles/what-is-nodejs-for-java-developers
#https://dzone.com/articles/serverless-development-with-nodejs-aws-lambda-and?fromrel=true
#https://aws.amazon.com/getting-started/projects/deploy-nodejs-web-app/
#https://blog.couchbase.com/create-continuous-deployment-pipeline-nodejs-jenkins/
#https://github.com/gruntjs/grunt/issues/829
#https://gruntjs.com/api/grunt.util#grunt.util.spawn
#https://dontkry.com/posts/code/grunt-tricks2.html
#https://strongloop.com/strongblog/node-js-java-getting-started/
